bash data_collection/bashs/weather-0/routes_town03_short.sh & 
bash data_collection/bashs/weather-1/routes_town03_short.sh & 
bash data_collection/bashs/weather-2/routes_town03_short.sh & 
bash data_collection/bashs/weather-3/routes_town03_short.sh & 
bash data_collection/bashs/weather-4/routes_town03_short.sh & 
bash data_collection/bashs/weather-5/routes_town03_short.sh & 
bash data_collection/bashs/weather-6/routes_town03_short.sh & 
bash data_collection/bashs/weather-7/routes_town03_short.sh & 
bash data_collection/bashs/weather-8/routes_town03_short.sh & 
